//! `host-capabilities.cln` emission (CLNH-44..47).
//!
//! The manifest is what tooling — `cln`, the LSP, the framework's capability
//! checker, AI assistants via MCP — reads to know which capabilities are *live*
//! in a deployment, as opposed to which ones the host software could support.
//! That distinction is the whole point: `host.wit` says "this host can do X",
//! the manifest says "X is turned on here, right now".
//!
//! Schema source of truth:
//! `foundation/02 components/hosts/clean-host-core/schema/host-capabilities.cln.md`.

use std::fmt::Write as _;
use std::path::Path;

use crate::config::HostConfig;
use crate::HostError;

/// Whether a capability is usable in this deployment (CLNH spec §9.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapabilityStatus {
    /// Bridge composed and load-time validation passed.
    Active,
    /// Composed but switched off by concrete-host policy.
    Disabled,
    /// No bridge composed for this interface.
    Unavailable,
}

impl CapabilityStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Disabled => "disabled",
            Self::Unavailable => "unavailable",
        }
    }
}

#[derive(Debug, Clone)]
pub struct CapabilityEntry {
    pub interface: String,
    pub status: CapabilityStatus,
    /// Bridge component path, when one is composed.
    pub component: Option<String>,
    /// Why a capability is disabled or unavailable. Surfaced verbatim to
    /// developers and AI assistants (Platform 16 §16.12.3), so it must read as
    /// an explanation, not an error code.
    pub reason: Option<String>,
}

#[derive(Debug, Clone)]
pub struct CapabilitiesManifest {
    pub host_name: String,
    pub host_version: String,
    pub generator_version: String,
    pub deployment: Option<String>,
    pub deployment_mode: String,
    pub guest_name: String,
    pub world: String,
    pub capabilities: Vec<CapabilityEntry>,
}

impl CapabilitiesManifest {
    pub fn new(config: &HostConfig, capabilities: Vec<CapabilityEntry>) -> Self {
        Self {
            host_name: config.host.name.clone(),
            host_version: config.host.version.clone(),
            generator_version: env!("CARGO_PKG_VERSION").to_string(),
            deployment: config.host.deployment.clone(),
            deployment_mode: config.host.deployment_mode.as_str().to_string(),
            guest_name: config.guest.name.clone(),
            world: config.guest.world.clone(),
            capabilities,
        }
    }

    /// Render the manifest.
    ///
    /// CLNH-78 versions the format through the generator comment, and consumers
    /// must tolerate unknown fields.
    pub fn render(&self) -> String {
        let mut out = String::new();
        let _ = writeln!(
            out,
            "// Generated by clean-host-core {}",
            self.generator_version
        );
        let _ = writeln!(
            out,
            "// Do not edit; regenerated on every compose and reload."
        );
        let _ = writeln!(out);

        let _ = writeln!(out, "host:");
        let _ = writeln!(out, "\tname = \"{}\"", self.host_name);
        let _ = writeln!(out, "\tversion = \"{}\"", self.host_version);
        if let Some(d) = &self.deployment {
            let _ = writeln!(out, "\tdeployment = \"{d}\"");
        }
        let _ = writeln!(out, "\tdeployment_mode = \"{}\"", self.deployment_mode);
        let _ = writeln!(out);

        let _ = writeln!(out, "guest:");
        let _ = writeln!(out, "\tname = \"{}\"", self.guest_name);
        let _ = writeln!(out, "\tworld = \"{}\"", self.world);
        let _ = writeln!(out);

        let _ = writeln!(out, "capabilities:");
        for cap in &self.capabilities {
            let _ = writeln!(out, "\t\"{}\":", cap.interface);
            let _ = writeln!(out, "\t\tstatus = \"{}\"", cap.status.as_str());
            if let Some(c) = &cap.component {
                let _ = writeln!(out, "\t\tcomponent = \"{c}\"");
            }
            if let Some(r) = &cap.reason {
                let _ = writeln!(out, "\t\treason = \"{}\"", escape(r));
            }
        }
        out
    }

    /// Write the manifest to disk.
    ///
    /// CLNH-47: a write failure is a startup error. A manifest that silently
    /// isn't there defeats every consumer that depends on it.
    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), HostError> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent).map_err(|e| {
                    HostError::Config(format!(
                        "cannot create directory for capability manifest `{}`: {e}",
                        parent.display()
                    ))
                })?;
            }
        }
        std::fs::write(path, self.render()).map_err(|e| {
            HostError::Config(format!(
                "cannot write capability manifest `{}`: {e}",
                path.display()
            ))
        })
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> HostConfig {
        HostConfig::parse(
            r#"
[host]
name = "clean-server"
version = "0.1.0"
component-model = "0.3.0"
deployment = "prod-eu-1"

[guest]
name = "app"
wasm = "./app.wasm"
world = "server"
"#,
            "/srv/host.toml",
        )
        .unwrap()
    }

    #[test]
    fn renders_generator_comment_and_status_values() {
        let m = CapabilitiesManifest::new(
            &config(),
            vec![
                CapabilityEntry {
                    interface: "clean:host/routing@0.1.0".into(),
                    status: CapabilityStatus::Active,
                    component: None,
                    reason: None,
                },
                CapabilityEntry {
                    interface: "clean:session/store@0.1.0".into(),
                    status: CapabilityStatus::Unavailable,
                    component: None,
                    reason: Some("no [bridges] entry configured".into()),
                },
            ],
        );
        let text = m.render();
        assert!(text.starts_with("// Generated by clean-host-core "));
        assert!(text.contains("status = \"active\""));
        assert!(text.contains("status = \"unavailable\""));
        assert!(text.contains("no [bridges] entry configured"));
        assert!(text.contains("deployment = \"prod-eu-1\""));
    }

    #[test]
    fn write_creates_missing_parent_directories() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested/deeper/host-capabilities.cln");
        let m = CapabilitiesManifest::new(&config(), vec![]);
        m.write(&path).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn quotes_in_a_reason_do_not_break_the_field() {
        let m = CapabilitiesManifest::new(
            &config(),
            vec![CapabilityEntry {
                interface: "clean:kv/store@0.1.0".into(),
                status: CapabilityStatus::Disabled,
                component: None,
                reason: Some("admin toggled \"kv\" off".into()),
            }],
        );
        assert!(m
            .render()
            .contains(r#"reason = "admin toggled \"kv\" off""#));
    }
}
